# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Push a new beta build to TestFlight"
  lane :beta do

    match(git_url: "git@github.com-lv:lomaverde/match_ios.git",
          type: "appstore",
          app_identifier: "com.lomavede.CoolApp")

    increment_build_number(xcodeproj: "CoolApp.xcodeproj")
    sync_code_signing

    disable_automatic_code_signing(path: "CoolApp.xcodeproj")

    gym(
      scheme: "CoolApp",
      workspace: "uCoolApp.xcworkspace",
      clean: true,
      output_name: "coolApp.ipa",
      configuration: "Release",
      export_method: "app-store" )

    enable_automatic_code_signing(path: "CoolApp.xcodeproj")
    upload_to_testflight
  end

  lane :certificates do
    match(app_identifier: ["com.lomavede.CoolApp"], readonly: true)
  end

end
